### ISSUE TITLE
Add previous tab to event

### ISSUE THREAD

**Issue by Log1x** [cferdinandi/tabby#105]
I was curious if you could add the previous tab to the `tabby` event? My personal use-case is so I can remove a `is-active` class from the old tab when a new tab is selected. I dropped `event` to a `console.log()` as well as skimmed over the code in case I was missing something, but I don't believe there is currently a way.

Thanks in advance.

**Comment by cferdinandi** [comment]
That's a good idea! Let me look into it...

As for your error, can you open a new issue with a reduced test case for that one, please?

**Comment by Log1x** [comment]
Will do! Thanks!

**Comment by cferdinandi** [comment]
This is addressed with v12.0.3
