### ISSUE TITLE
TypeError when no tabs exist on a page

### ISSUE THREAD

**Issue by Log1x** [cferdinandi/tabby#106]
Currently Tabby is throwing a TypeError when it is being included on a page that doesn't have the selector (e.g. `[data-tabs]`) present.

You can see this [here](https://codepen.io/Log1x/pen/XQXRjM) using your browsers console (Codepen's console does not show it).

The example above is the default Tabby example with `data-tabs` simply removed from the `ul`.

```js
Uncaught TypeError: Cannot read property 'addEventListener' of null at init
```

**Comment by cferdinandi** [comment]
Ah gotcha. Yea, it should probably bail before then, huh? Thanks for this. Will fix.

**Comment by cferdinandi** [comment]
The more I think about it, the error is a feature in that it tells you you've done something wrong. Decided to "won't fix" this one. Sorry!
