### ISSUE TITLE
Stop video when tab is inactive

### ISSUE THREAD

**Issue by bogdanptr** [cferdinandi/tabby#107]
Hello! I was wondering if there is a way to stop youtube embedded videos when a tab is inactive.

**Comment by cferdinandi** [comment]
You should be able to do this with [the `tabby` events](https://github.com/cferdinandi/tabby#custom-events) and [the method described in this article](https://gomakethings.com/stopping-youtube-vimeo-and-html5-videos-with-javascript/).

Something like this.

```js
var stopVideo = function ( element ) {
	var iframe = element.querySelector( 'iframe');
	var video = element.querySelector( 'video' );
	if ( iframe !== null ) {
		var iframeSrc = iframe.src;
		iframe.src = iframeSrc;
	}
	if ( video !== null ) {
		video.pause();
	}
};

document.addEventListener('tabby', function (event) {
	stopVideo(event.target);
}, false);
```
