### ISSUE TITLE
CSS file not available via CDN

### ISSUE THREAD

**Issue by alessandro-newzoo** [cferdinandi/tabby#112]
From your docs:

```
<!-- Get a specific version -->
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/cferdinandi/tabby@12.0.0/dist/css/tabby.min.css">
<script src="https://cdn.jsdelivr.net/gh/cferdinandi/tabby@12.0.0/dist/js/tabby.polyfills.min.js"></script>
```

but unfortunately this link gives a 404: https://cdn.jsdelivr.net/gh/cferdinandi/tabby@12.0.0/dist/css/tabby.min.css

and if I look inside the /dist folder, there's no file named `tabby.min.css`:

![image](https://user-images.githubusercontent.com/47320294/75327742-33b6dd80-587d-11ea-85fa-2101ccb28f39.png)

which file am I supposed to use?

Thanks a lot for this amazing library :)

**Comment by cferdinandi** [comment]
Oh yep, sorry. I'll update the docs. Pick the regular or vertical version depending on which UI you want, or skip them and roll your own.

**Comment by cferdinandi** [comment]
Updated, thanks!
