### ISSUE TITLE
Docs incomplete

### ISSUE THREAD

**Issue by jenstornell** [cferdinandi/tabby#41]
I copy pasted the example from the docs "List Links". It gives:

    Uncaught TypeError: Cannot read property 'parentNode' of undefined

The example is missing the two last tabs-pane.

**Comment by cferdinandi** [comment]
There are `...` indicating that the content is abridged. Got it working?

**Comment by jenstornell** [comment]
Yes, seems awesome. I really like the simplicity, bloatless and the not jQuery approach.

**Comment by cferdinandi** [comment]
Excellent, and sorry for the confusion!
