### ISSUE TITLE
1 Navi 2 Tabs

### ISSUE THREAD

**Issue by Zariss** [cferdinandi/tabby#46]
Hi there againe cferdinandi.

my last problem worked out after your fix. Thanks for that againe. But now i got a question regarding multible tabs thats being controled by 1 navigation. First i just tried if it's possible at all... result the first Tab changes like it should. The second Tab area works fine on adding the calss to show the Tab. But it dosnt remove from the previous active one the style to hide it.

I know, #ID's arent meant to use more then once on a page but... i needed to try anyways. Do you know what i can change to get this working? Since adding works fine but removing not.

**Comment by cferdinandi** [comment]
You cannot use an ID more than once, but at least with version 10 (released after your last issue was opened), you can control multiple tab content areas from a single tab navigation.
