### ISSUE TITLE
Page scrolls when click active tab

### ISSUE THREAD

**Issue by mphm** [cferdinandi/tabby#57]
Clicking on each tabs is fine, and changes the pane accordingly. I just don't like it when clicking the tab when its active, scrolls the page to the pane. Possible that an option can be created to disable this? This can be tested by going to the demo http://cferdinandi.github.io/tabby/#tabb and making the height of the browser < 330.

**Comment by cferdinandi** [comment]
I agree. This is a bug that didn't show up in testing, and an easy one to fix. Thanks for letting me know. I'll address this asap.

**Comment by cferdinandi** [comment]
Fixed with v 10.0.5: https://github.com/cferdinandi/tabby/pull/58
