### ISSUE TITLE
Feature Request: Hide pane when tab is active

### ISSUE THREAD

**Issue by mphm** [cferdinandi/tabby#60]
This might not fit with your project, but was wondering if there can be a new option where the pane can still be toggled on/off when clicking the active tab.

**Comment by cferdinandi** [comment]
This seems more like a task for [Houdini's accordion functionality](http://cferdinandi.github.io/houdini/#accordions), which already behaves that way and can be styled however you'd like.

**Comment by jenstornell** [comment]
A little late but, maybe what you are asking for is this?

https://github.com/cferdinandi/tabby/issues/78
