### ISSUE TITLE
Possible to disable back/forward history of tabs.

### ISSUE THREAD

**Issue by jfeust** [cferdinandi/tabby#75]
I'm using tabby almost like a "toggle" on the page that a user might switch between tabs many times during a pageview.  If they've done it 10+ times, using the back button becomes extremely tedious. Is there a way (option) to disable the back button history on tab changes?

**Comment by cferdinandi** [comment]
Not with the current version. That's a feature designed to promote accessibility.

However, I believe v10.x does not update the URL. You can get it (and view the docs for it) here: https://github.com/cferdinandi/tabby/tree/4c281715ad237fd405172544c62139cf28e01f35
