### ISSUE TITLE
Disable hash?

### ISSUE THREAD

**Issue by jenstornell** [cferdinandi/tabby#79]
I did not find how to disable using hash. Sometimes hash are good but sometimes not. I have many functions that could leave traces in the url but I prefer to keep things clean.

Is it possible in a simple way to not use hash in the url?

**Comment by cferdinandi** [comment]
Not supported. The hash is what powers the change, and progressively enhances what are otherwise normal anchor links.

**Comment by jenstornell** [comment]
As much as I like the idea of Tabby, some things did simply not work out for me like the hash problem. I decided to go for an own javascript plugin.

**Tabbis was born:**
https://github.com/jenstornell/tabbis.js

- Tiny filesize
- Simple setup
- Remember tabs (localStorage)
- Callback support
- Unlimited tab sets
- Unlimited nesting
- No jQuery
- No bloat
- No hash

Now why am I telling you this? Because if you are inspired by anything in Tabbis, feel free to snag ideas from it. You and Tabby have given me ideas, so I'm now offering the same thing.

![screenshot](https://cloud.githubusercontent.com/assets/927011/22243224/aad19cb4-e226-11e6-926a-c5410bc94857.gif)

**Super simple**

```html
<div data-tabs>
  <div>Tab1</div>
  <div>Tab2</div>
  <div>Tab3</div>
</div>

<div data-panes>
  <div>Pane1</div>
  <div>Pane2</div>
  <div>Pane3</div>
</div>
```

Thanks for the word.
