### ISSUE TITLE
Switch tab makes the page jump

### ISSUE THREAD

**Issue by jenstornell** [cferdinandi/tabby#80]
I'm using Tabby 11.2.0 and have no other javascripts. The only CSS I have is display: block and display: none. Maybe it's the hash?

![tabby](https://cloud.githubusercontent.com/assets/927011/22154957/eebc008c-df2d-11e6-9154-7d066baeb5fc.gif)

**Comment by cferdinandi** [comment]
Working demo please.

**Comment by jenstornell** [comment]
It noticed that Tabby was not a perfect fit for me so I've developed an own vanilla js plugin for it. It means I can't provide more information to this topic, sorry. I'm closing it.
