### ISSUE TITLE
Browser History

### ISSUE THREAD

**Issue by shornuk** [cferdinandi/tabby#81]
Anyway to implement keeping the deep linking but stop the browser keeping the history of the tabs being opened?

**Comment by cferdinandi** [comment]
Nope

**Comment by shornuk** [comment]
No probs. Never come across it as being the wanted/expected behaviour, but if it's fundamental to it then no worries.

**Comment by cferdinandi** [comment]
It's an accessibility thing, so keyboard users can navigate between tabs via the browser forward/back buttons.

This was added in v11.x, though, so if you [grabbed v10.x](https://github.com/cferdinandi/tabby/releases/tag/v10.2.0), you can probably bolt in deep linking with `toggleTab()` method without the browser history.

**Comment by shornuk** [comment]
Nice, thanks!
