### ISSUE TITLE
Is all of this strictly necessary?

### ISSUE THREAD

**Issue by shenanigans** [cferdinandi/tabby#89]
I've just been doing [this](https://jsfiddle.net/1L1L2nwt/2/). Do you know of any accessibility issues with this method?

**Comment by cferdinandi** [comment]
That's a better question for @scottaohara. He'll hopefully chime in here, though I am going to close this issue.

There's plenty of resources and articles around the a11y implications of CSS-only approaches to things like this, and it's a bit off topic in the context of this specific script.

**Comment by scottaohara** [comment]
@shenanigans while CSS only solutions are often clever, they more often do not provide experiences that users of keyboard and/or assisitive technology would expect.

per tabs, you can see what the official ARIA best practices specification outlines as the necessary information/experience one needs to provide, to create an accessible tab component - https://www.w3.org/TR/wai-aria-practices/#tabpanel
