### ISSUE TITLE
Fix README for point to correct npm package

### ISSUE THREAD

**Issue by Amareis** [cferdinandi/tabby#90]
`npm install cferdinandi/tabby` is wrong, you need to `npm install tabbyjs`

**Comment by cferdinandi** [comment]
No its not. That points to this GitHub repository, and installing from GitHub is supported by NPM. I am not yet actively maintaining this project on the NPM registry.

**Comment by BariqDharmawan** [comment]
Hi I am sorry for comment on this old issue. But I can't use tabby with `npm install cferdinandi/tabby` or `npm install tabbyjs` and import the library with `import 'tabbyjs'` on my JS. Am I missing something?
