### ISSUE TITLE
Multiple instances? 

### ISSUE THREAD

**Issue by Und3Rdo9** [cferdinandi/tabby#95]
Thanks for great plugin! Is it possible to have multiple instances of tabby with different settings? I tried assigning tabby to differently named variables, but I can't get it to work. 

Thanks in advance for any help.

**Comment by cferdinandi** [comment]
Not yet. The plugin needs a refactor to support this, and it's on my roadmap. I'll keep this open as a feature request so you can get an update when it's available.

**Comment by bwasilewski** [comment]
It would also be great to be able to nest tab groups.

**Comment by cferdinandi** [comment]
A refactor should support this, but, candidly from a UX perspective, that's a horrible idea.

**Comment by bwasilewski** [comment]
Thanks for your advice, I would still like to see it supported if possible!

**Comment by cferdinandi** [comment]
This will be released tomorrow

**Comment by cferdinandi** [comment]
Done: https://github.com/cferdinandi/tabby/releases/tag/v12.0.0
